import type { Metadata } from "next";
import "./globals.css";
import { alteDIN } from "@/fonts";
import AppContextProvider from "@/contexts/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body
          className={`${alteDIN.variable} antialiased`}
          style={{ touchAction: "none" }}
        >
          {children}
        </body>
      </html>
    </AppContextProvider>
  );
}
