import type { Metadata } from "next";
import "@/assets/css/globals.css";
import { alteDIN } from "@/fonts";
import AppContextProvider from "@/contexts/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ Component, pageProps }: any) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body
          className={`${alteDIN.variable} antialiased`}
          style={{ touchAction: "none" }}
        >
          <div id="phantom-container" className="space-x-8 h-20 h-40 hidden" />
          <Component {...pageProps} />
        </body>
      </html>
    </AppContextProvider>
  );
}
